import type { Metadata } from "next"
import "./globals.css"
import { Lora } from "next/font/google"

const font = Lora({
	weight: "500",
	subsets: ["latin"],
	variable: "--font-lora",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${font.variable} antialiased w-full`}>
				{children}
			</body>
		</html>
	)
}
